### ISSUE TITLE
Kanban Board 

### ISSUE THREAD

**Issue by Beardless-sheik** [Beardless-sheik/Recipe-Ruby#12]
[Github Project Link](https://github.com/Beardless-sheik/Recipe-Ruby/projects/1)

- I am alone in this team so have taken up the tasks.

**Comment by codepantha** [comment]
Hi @Beardless-sheik 👋 , 

Your project is complete! There is nothing else to say other than... it's time to start your project :shipit:
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
